export const CREATE_CHANNEL = 'CREATE_CHANNEL'
export const NET_STATUS = 'NET_STATUS'
export const LOADING_FLAG = 'LOADING_FLAG'
export const ACQUIRE_QRCODE = 'ACQUIRE_QRCODE'
export const LOG_IN='LOG_IN'